### ISSUE TITLE
edmond serves css at port 8080

### ISSUE THREAD

**Issue by xrotwang** [MPDL-Collections/edmond#69]
css for edmond.mpdl.mpg.de is served from [port 8080](http://edmond.mpdl.mpg.de:8080/theme/stylesheets/bright.css), which can (and does) cause problems when edmond is accessed in an environment which does not allow outgoing connections on port 8080 - which isn't completely uncommon.

**Comment by xrotwang** [comment]
Any plans for fixing this? I'm just now experiencing this problem again.

**Comment by wilhelmfrank** [comment]
Fixed!

On 01/13/2016 09:27 AM, Robert Forkel wrote:
>
> Any plans for fixing this? I'm just now experiencing this problem again.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MPDL-Collections/edmond/issues/69#issuecomment-171214579>.
>

-- 
Wilhelm Frank				E-Mail: frank@mpdl.mpg.de
					Tel:    +49-89-38602-226
Max Planck Digital Library (MPDL)	Fax:    +49-89-38602-280
Amalienstr. 33, D-80799 Munich, GERMANY http://www.mpdl.mpg.de
